version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      -  ~/.composer-docker/cache:/root/.composer/cache:delegated
      -  ./:/app:delegated
    ports:
      -  '8080:80'
    networks:
      -  yii-basic
  db:
    image: mysql:5.7
    restart: always
    environment:
      -  MYSQL_DATABASE=raptor
      -  MYSQL_USER=elvindev
      -  MYSQL_PASSWORD=12862003
      -  MYSQL_ROOT_PASSWORD=1234
    ports:
      -  '3306:3306'
    expose:
      -  '3306'
    volumes:
      -  my-db:/var/lib/mysql     
    networks:
      -  yii-basic 
  volumes:
    my-db:
  networks:
    yii-basic:
      driver: bridge
